### ISSUE TITLE
Think about how to speed up decodes while running

### ISSUE THREAD

**Issue by edeno** [edeno/Roumis_2018#4]
Decoding the position of the animal while the animal is running the maze takes a long time. We need this to quantify the quality of the decoding. It would be nice to speed this process up.

Some possibilities:
+ [ ] Bigger time bin sizes: We can increase the size of time bins up to the refactory period (~2 ms is safe). We typically want 1 spike per bin for the poisson assumptions to hold. Not sure what happens if we make these bins larger.
+ [ ] Use cython or numba for the essential parts of code. @daliu87 do you have any thoughts on how hard this is to do?

**Comment by daliu87** [comment]
For single thread/core speedup, I've tried cythonizing my numpy code but I don't really see any improvements.  The only place I'd imagine cython+numpy could offer an improvement is the step evaluating the state transition matrix, but I haven't tried that yet.  It's pretty straightforward with Cython, in theory looping through numpy calculations should be faster.  I haven't looked into numba yet.

Another place where I was able to improve performance is in estimating the observation from the encoding model, rather than estimating the distribution of a single mark at a time I was able to vectorize across all marks.  This requires using 3-dim matrices, so it becomes a computation vs. memory trade off.  I then parallelized this code with Dask and used chunking to manually optimize memory usage.

I'm working on parallelizing the other steps of the algorithm too, using Dask.  I think that's been giving the most fruitful speedups. 

On bigger bin sizes, I've seen that qualitatively, the decodes are consistent with 10 ms bins.  I'm not exactly how this violates the Poisson assumptions being made, do you have any insights on this?  I know one problem with having more than one spike per bin is you have to assume each spike is independent, which may not be true anymore.

**Comment by edeno** [comment]
@daliu87 That makes sense. I've tried evaluating the likelihood all at once in the `replay_identification` package I've been developing for Long Tao's code, but wasn't quite happy with the computation vs. memory trade off. This was for a much larger matrix than for the marks, so maybe with marks it'll be better.

With respect to numba, you might find this article of interest: http://matthewrocklin.com/blog/work/2018/01/30/the-case-for-numba

You're right -- the independence of spikes assumption is what is being violated. One of the key Poisson assumptions is that the process is memoryless (events are independent of each other). Having multiple spikes in one bin destroys this. The absence of spikes in a bin provides information to the likelihood. By binning too coarsely, you lose that information.

**Comment by daliu87** [comment]
Interesting about Numba, I'll have to give it a try.  Given what I've read, I'd expect it to speed up loops with numpy operations (e.g. state transition evaluations) but not for vectorized operations?  Probably performance similar to cython but cleaner syntactically and without a compile step.

About larger bin sizes, I believe in the NSpike data you guys have, our 'refractory period' is 40 samples (at 30kHz) so 1.33ms.  For future mountain sort data it's 10 samples (at 30kHz) for tetrodes.  Practically if we did choose a larger bin size (e.g. 10ms), what qualitative differences would you expect to see compared with 1ms bins?  My intuition is since behavior is evolving on the timescale of seconds and ripple events are 50-200ms, the results of classifying the replay types would be similar even with violating those assumptions.  Does this seem right to you?  (Of course we'll have to test it and see)

**Comment by daliu87** [comment]
I just tried speeding things up with Cython and Numba and no luck.  I was focusing on the iterative code calculating the posterior from the observation, transition matrix, and last posterior.

No noticeable difference with using using numba, although I haven't tried all the techniques they suggest.  I did a lot of tries with Cython, pushing the main for loop into Cython.  Some techniques (e.g. swhich to C-types arrays and custom arithmetics) made things much slower.

Right now testing with a 15 minute dataset, my encoding model takes 3 minutes to generate observations, and the decoding steps that about another 3 minutes.  So speedup from realtime is roughly 2x.

**Comment by daliu87** [comment]
Figured out why I was seeing slow downs in some of my Cython implementation.  Numpy uses BLAS/LAPACK for matrix operations, which is parallelized.  By customizing arithmetic (avoiding numpy) it makes operations single threaded and much slower.  This makes a huge difference for large matrices and vectors (>50 rows).  If you're dealing with smaller matrices/ (< 50) it may still be worth cythonizing into C arithmetic, because the numpy overhead outweights any gains from BLAS/LAPACK.

**Comment by edeno** [comment]
Yeah -- I think I've run into similar issues. It's tricky beating numpy because it is pretty well written. I'm surprised the Cython techniques made the Cython loop slower though.

**Comment by daliu87** [comment]
Yeah, I followed these guides:
https://pandas.pydata.org/pandas-docs/stable/enhancingperf.html
http://cython.readthedocs.io/en/latest/src/tutorial/numpy.html

But I think our time spent looping is relatively small (~100,000) compared with the amount of time multiplying np arrays (~450x450), so I see minimal speedups.
